#include "c_gui_chat_enum.h"

map <string, int> GUI_CHAT;
map <int, string> rGUI_CHAT;
map <int ,string> GUI_CHAT_COLOR;

void dfGUI_CHAT(void){

    GUI_CHAT.clear();
    GUI_CHAT["SYSTEM" ] = CHANNEL_SYSTEM;
    GUI_CHAT["CONSOLE"] = CHANNEL_CONSOLE;
    GUI_CHAT["LOCAL"  ] = CHANNEL_LOCAL;
    GUI_CHAT["TRADE"  ] = CHANNEL_TRADE;
    GUI_CHAT["GENERAL"] = CHANNEL_GENERAL;
    GUI_CHAT["WHISPER"] = CHANNEL_WHISPER;
    GUI_CHAT["PARTY"  ] = CHANNEL_PARTY;
    GUI_CHAT["RAID"   ] = CHANNEL_RAID;
    GUI_CHAT["SAY"    ] = CHANNEL_SAY;
    GUI_CHAT["YELL"   ] = CHANNEL_YELL;
    GUI_CHAT["CLAN"   ] = CHANNEL_CLAN;
    GUI_CHAT["CUSTOM" ] = CHANNEL_CUSTOM;

    rGUI_CHAT.clear();
    rGUI_CHAT[CHANNEL_SYSTEM  ] = "SYSTEM";
    rGUI_CHAT[CHANNEL_CONSOLE ] = "CONSOLE";
    rGUI_CHAT[CHANNEL_LOCAL   ] = "LOCAL";
    rGUI_CHAT[CHANNEL_TRADE   ] = "TRADE";
    rGUI_CHAT[CHANNEL_GENERAL ] = "GENERAL";
    rGUI_CHAT[CHANNEL_WHISPER ] = "WHISPER";
    rGUI_CHAT[CHANNEL_PARTY   ] = "PARTY";
    rGUI_CHAT[CHANNEL_RAID    ] = "RAID";
    rGUI_CHAT[CHANNEL_SAY     ] = "SAY";
    rGUI_CHAT[CHANNEL_YELL    ] = "YELL";
    rGUI_CHAT[CHANNEL_CLAN    ] = "CLAN";
    rGUI_CHAT[CHANNEL_CUSTOM  ] = "CUSTOM";

    GUI_CHAT_COLOR.clear();
    GUI_CHAT_COLOR[CHANNEL_SYSTEM]  = "^6";
    GUI_CHAT_COLOR[CHANNEL_CONSOLE] = "^7";
    GUI_CHAT_COLOR[CHANNEL_LOCAL]   = "^8";
    GUI_CHAT_COLOR[CHANNEL_TRADE]   = "^2";
    GUI_CHAT_COLOR[CHANNEL_GENERAL] = "^3";
    GUI_CHAT_COLOR[CHANNEL_WHISPER] = "^4";
    GUI_CHAT_COLOR[CHANNEL_PARTY]   = "^5";
    GUI_CHAT_COLOR[CHANNEL_RAID]    = "^6";
    GUI_CHAT_COLOR[CHANNEL_SAY]     = "^1";
    GUI_CHAT_COLOR[CHANNEL_YELL]    = "^2";
    GUI_CHAT_COLOR[CHANNEL_CLAN]    = "^3";
    GUI_CHAT_COLOR[CHANNEL_CUSTOM]  = "^4";
};
